import { Sparkles, FileText } from 'lucide-react';

const SummaryBox = ({ summary }) => {
  return (
    <div className="glass-card overflow-hidden">
      <div className="bg-slate-900 px-8 py-4 flex items-center gap-3">
        <Sparkles className="text-primary h-5 w-5 animate-pulse" />
        <h3 className="text-white font-bold text-lg">AI Developer Analysis</h3>
      </div>
      <div className="p-8 bg-linear-to-br from-white to-slate-50">
        <div className="flex gap-4">
          <div className="hidden md:block">
            <div className="bg-primary/10 p-3 rounded-xl">
              <FileText className="text-primary h-6 w-6" />
            </div>
          </div>
          <div className="flex-1">
            <p className="text-slate-700 leading-relaxed text-lg whitespace-pre-wrap italic">
              "{summary || 'No summary available for this user.'}"
            </p>
            <div className="mt-6 flex items-center gap-2">
              <div className="h-px flex-1 bg-slate-200"></div>
              <span className="text-[10px] uppercase tracking-widest text-slate-400 font-bold">Generated by GitAnalytica AI</span>
              <div className="h-px flex-1 bg-slate-200"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default SummaryBox;
